objects/Expense__c.object
<CustomObject>
    <label>Expense</label>
    <nameField>
        <label>A Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ExpenseMember__c.object
<CustomObject>
    <fields>
        <fullName>Contribution_Amount__c</fullName>
        <label>Contribution Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expense__c</fullName>
        <label>Expense</label>
        <referenceTo>Expense__c</referenceTo>
        <relationshipLabel>ExpenseMember</relationshipLabel>
        <relationshipName>ExpenseMember</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>ExpenseMember</relationshipLabel>
        <relationshipName>Member</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ExpenseMember</label>
    <nameField>
        <label>ExpenseMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExpenseMember</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ExpenseExtension.cls
public with sharing class ExpenseExtension {
    
    public Expense__c expObj{get;set;}//The "get" method is used to pass data from your Apex code to your Visualforce page and "set" method is used to pass values from your visualforce page to the controller.
    
    public ExpenseExtension(ApexPages.StandardController controller) {
        expObj = (Expense__c)controller.getRecord();// getRecord() method used for getting the created record id from the controller
    }
        public List<ExpenseMember__c>getExpMembers(){
        return [Select Id,Name,Member__r.First_Name__c,Member__r.Last_Name__c,Contribution_Amount__c from ExpenseMember__c where Expense__c =: expObj.Id];
       //using query fetching the values from database
    }
    
    
}